### ISSUE TITLE
Postman Dump of all the USIS api endpoints I could find

### ISSUE THREAD

**Issue by NaiveInvestigator** [nur-zaman/better-usis#3]
[Postman Data dump.zip](https://github.com/nur-zaman/better-usis/files/14540259/Postman.Data.dump.zip)

i thought maybe this might prove useful to you? Please continue on this vaiya !!

P.S: Could we Ayesha library integration too ;0

Edit: To see it just import it to Postman :>

**Comment by nur-zaman** [comment]
Thank you <3 
https://www.bracu.ac.bd/academic/spring/2023/rss.xml is really useful.
Currently I'm hard coding the academic calendar in [data.ts](https://github.com/nur-zaman/better-usis/blob/master/constants/data.ts) 

Can you help in parsing the data dynamically from the url ?

**Comment by NaiveInvestigator** [comment]
glad u found something in use there. That zip filr also includes api endpoints exclusive to the bracu app so thought those might be handy too.

> Can you help in parsing the data dynamically from the url ?

I sadly never worked with JavaScript or Typescript. I only know a lil bit of python but I'll see wot i can cook up. :0 it hopefully should not be too hard ;-;

keeping it here for reference and so that i dont forget about them lol:>

https://developer.mozilla.org/en-US/docs/Web/XML/Parsing_and_serializing_XML

p.s : do u have any objections in adding [fast-xml-parser](https://www.npmjs.com/package/fast-xml-parser) as a depedency? But then again ig it might be overkill to add it just parse one xml file.

**Comment by nur-zaman** [comment]
Yeah the app endpoints are useful too. thanks again.

about using a xml parser I dont have a that much issue but it would better if you could do it with [cheerio](https://cheerio.js.org/docs/advanced/configuring-cheerio) 's xml parser, as I've already added it to parse some of the dom in the site.

you can look at `usis` folder and check out some of the API calls  especially this [usisParseAdvisingCourses.ts](https://github.com/nur-zaman/better-usis/blob/master/usis/usisParseAdvisingCourses.ts) this parse data from https://usis.bracu.ac.bd/academia/admissionRequirement/getAvailableSeatStatus which doesn't need authentication.

One more thing I've noticed that I forgot to push .env.local 's example file.

be sure to create a .env.local file in the root directory and put these content in it 

```env
NEXTAUTH_URL = http://localhost:3000
NEXTAUTH_SECRET=secret
```

**Comment by nur-zaman** [comment]
I'll Close this one and make a separate issue #4  for the feature.
