### ISSUE TITLE
Text clips beyond the box

### ISSUE THREAD

**Issue by NaiveInvestigator** [nur-zaman/better-usis#6]
![image](https://github.com/nur-zaman/better-usis/assets/72654596/5cb4eb87-d6a0-4e5c-8cd1-ebabb6cd07f4)

Yeah i happen to have a rare faculty whose initials are 4 letters lol.

**Comment by nur-zaman** [comment]
Will fixed with the next merge. Thank you for reporting.

**Comment by nur-zaman** [comment]
Fixed #8
